# Generated by Django 4.1 on 2022-08-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flowsheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Leak_Present",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=5
                    ),
                ),
                (
                    "Reflux",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=5
                    ),
                ),
                (
                    "desd",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=5
                    ),
                ),
                ("age_time_of_study", models.FloatField()),
                ("pvr", models.FloatField()),
                ("percent_full", models.FloatField()),
                (
                    "bladder_shape",
                    models.CharField(
                        choices=[
                            ("Smooth;Round", "Smooth;Round"),
                            ("Smooth", "Smooth"),
                            ("Smooth;Oblong", "Smooth;Oblong"),
                            ("Trabeculated;Oblong", "Trabeculated;Oblong"),
                            ("Unknown", "Unknown"),
                            ("Trabeculated", "Trabeculated"),
                            (
                                "Oblong;Few diverticula, generally smooth",
                                "Oblong;Few diverticula, generally smooth",
                            ),
                            ("Trabeculated;Round", "Trabeculated;Round"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pressure_25", models.FloatField()),
                ("pressure_half_ebc", models.FloatField()),
                ("press_three_four_ebc", models.FloatField()),
                (
                    "your_expert_rating",
                    models.CharField(
                        choices=[("Good", "Good"), ("Bad", "Bad"), ("Ugly", "Ugly")],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "flowsheet",
                "managed": True,
            },
        ),
    ]
