# Generated by Django 4.1 on 2022-08-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuapp", "0002_textfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextfileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upload", models.FileField(upload_to="vuapp/uploads/")),
                ("expected_bladder_capacity", models.FloatField()),
            ],
        ),
    ]
