# Generated by Django 4.1 on 2022-08-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuapp", "0003_textfileupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textfileupload",
            name="upload",
            field=models.FileField(upload_to=""),
        ),
    ]
