# Generated by Django 4.1 on 2022-09-08 20:52

from django.db import migrations, models
import vuapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("vuapp", "0004_alter_textfileupload_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomefileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dicom_upload",
                    models.FileField(
                        upload_to="textfilesupload/",
                        validators=[vuapp.models.validate_dicom_extension],
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Textfile",
        ),
        migrations.AlterField(
            model_name="textfileupload",
            name="upload",
            field=models.FileField(
                upload_to="textfilesupload/",
                validators=[vuapp.models.validate_file_extension],
            ),
        ),
    ]
